package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/universal-governance/ugc/engine/models"
)

type Emitter struct{}

func (e *Emitter) Emit(g *models.Governance, targetDir string) error {
	fmt.Println("Emitting Codex configuration...")

	var content strings.Builder
	content.WriteString(fmt.Sprintf("<!-- UGC-Source-Hash: %s -->\n\n", g.SourceHash))
	content.WriteString("# Universal Governance for OpenAI Codex\n\n")
	content.WriteString("This file is generated by UGC for OpenAI Codex. Codex reads repository `AGENTS.md` files as project guidance.\n\n")
	content.WriteString("## Canonical Governance Source\n\n")
	content.WriteString("- Source root: `.universal-governance/`\n")
	content.WriteString("- Mandatory entrypoint: `.universal-governance/AGENTS.md`\n")
	content.WriteString("- SOP index: `.universal-governance/SOPs/README.md`\n\n")
	content.WriteString("## Core Duties\n\n")
	content.WriteString("- Approval Gate: require explicit owner approval before gated, destructive, release, or architecture-changing work.\n")
	content.WriteString("- Stop Conditions: stop and report when source truth, approval, scope, or validation conflicts with the task.\n")
	content.WriteString("- Protected Surfaces: do not touch neighboring systems, secrets, cloud, billing, deploy, or git state unless approved.\n")
	content.WriteString("- Worklog: record material governance work in `Plans/worklog.md` when the active SOP requires it.\n")
	content.WriteString("- Destructive action warning: never overwrite, delete, reset, deploy, or publish without the applicable SOP approval.\n\n")
	content.WriteString("## Compiled Base Rules\n\n")
	content.WriteString(rewriteCodexSourcePaths(g.BaseRules))
	content.WriteString("\n\n## SOP Index\n\n")

	sops := append([]models.SOP(nil), g.SOPs...)
	sort.Slice(sops, func(i, j int) bool {
		return sops[i].Name < sops[j].Name
	})
	for _, sop := range sops {
		content.WriteString(fmt.Sprintf("- `%s`: `.universal-governance/SOPs/%s`\n", sop.Name, sop.Name))
	}

	if err := os.WriteFile(filepath.Join(targetDir, "AGENTS.md"), []byte(content.String()), 0644); err != nil {
		return err
	}
	if err := writeCodexConfig(g, targetDir); err != nil {
		return err
	}
	if err := writeCodexRules(g, targetDir); err != nil {
		return err
	}
	return writeCodexGovernanceSkill(g, targetDir)
}

func rewriteCodexSourcePaths(content string) string {
	content = strings.ReplaceAll(content, "`SOPs/", "`.universal-governance/SOPs/")
	content = strings.ReplaceAll(content, "(SOPs/", "(.universal-governance/SOPs/")
	return content
}

type codexPrefixRule struct {
	Pattern       []string
	Justification string
}

func writeCodexConfig(g *models.Governance, targetDir string) error {
	var content strings.Builder
	content.WriteString(fmt.Sprintf("# UGC-Source-Hash: %s\n", g.SourceHash))
	content.WriteString("# Project-local Codex config loads only after the project is trusted.\n")
	content.WriteString("approval_policy = \"on-request\"\n")
	content.WriteString("approvals_reviewer = \"user\"\n")
	content.WriteString("sandbox_mode = \"workspace-write\"\n")

	path := filepath.Join(targetDir, ".codex", "config.toml")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content.String()), 0644)
}

func writeCodexRules(g *models.Governance, targetDir string) error {
	var content strings.Builder
	content.WriteString(fmt.Sprintf("# UGC-Source-Hash: %s\n", g.SourceHash))
	content.WriteString("# Project-local Codex rules load only after the project is trusted.\n\n")

	for _, rule := range codexPrefixRules() {
		content.WriteString("prefix_rule(\n")
		content.WriteString(fmt.Sprintf("    pattern = %s,\n", starlarkStringList(rule.Pattern)))
		content.WriteString("    decision = \"forbidden\",\n")
		content.WriteString(fmt.Sprintf("    justification = %q,\n", rule.Justification))
		content.WriteString(")\n\n")
	}

	path := filepath.Join(targetDir, ".codex", "rules", "ugc.rules")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content.String()), 0644)
}

func writeCodexGovernanceSkill(g *models.Governance, targetDir string) error {
	var content strings.Builder
	content.WriteString("---\n")
	content.WriteString("name: ugc-governance\n")
	content.WriteString("description: Use for UGC-governed Codex work involving approvals, protected surfaces, releases, commits, pushes, audits, or worklog closure.\n")
	content.WriteString("---\n\n")
	content.WriteString("# UGC Governance Skill\n\n")
	content.WriteString(fmt.Sprintf("UGC-Source-Hash: `%s`\n\n", g.SourceHash))
	content.WriteString("This repo-local Codex skill provides the workflow layer for Universal Governance Compiler projects. It complements `AGENTS.md` and `.codex/rules/ugc.rules`; it does not replace either surface.\n\n")
	content.WriteString("## Canonical Sources\n\n")
	content.WriteString("- Repository guidance: `AGENTS.md`\n")
	content.WriteString("- Governance corpus: `.universal-governance/`\n")
	content.WriteString("- Corpus entrypoint: `.universal-governance/AGENTS.md`\n")
	content.WriteString("- SOP index: `.universal-governance/SOPs/README.md`\n")
	content.WriteString("- Build manifest: `.universal-governance/build_manifest.json`\n\n")
	content.WriteString("## Instructions\n\n")
	content.WriteString("1. Before material repository changes, read `AGENTS.md`, `.universal-governance/AGENTS.md`, and `.universal-governance/SOPs/README.md`.\n")
	content.WriteString("2. For architecture, governance, release, commit, push, deploy, destructive, or protected-surface work, read the relevant SOPs before acting.\n")
	content.WriteString("3. For approval-gated work, use the hash-bound approval packet flow from `.universal-governance/SOPs/UGC_APPROVAL_PACKET_SOP.md`.\n")
	content.WriteString("4. Use `ugc build --dry-run`, `ugc build`, `ugc audit`, and `ugc packet verify` when they are relevant to the requested governance task.\n")
	content.WriteString("5. Stop and report if approval text, packet hash, source truth, local worktree state, generated artifacts, or validation results conflict with the requested action.\n")
	content.WriteString("6. Before ending a material session, record required evidence in `Plans/worklog.md` when the active SOP requires worklog closure.\n\n")
	content.WriteString("## High-Value SOPs\n\n")
	for _, name := range []string{
		"UGC_REPOSCAN_AND_BOOTSTRAP_SOP.md",
		"UGC_APPROVAL_PACKET_SOP.md",
		"UGC_GOVERNANCE_CHANGE_SOP.md",
		"UGC_COMMIT_DEPLOY_PUSH_GUARDRAILS_SOP.md",
		"UGC_RELEASE_SOP.md",
		"UGC_WORKLOG_AND_SESSION_SOP.md",
		"UGC_WORKTREE_DISCIPLINE_SOP.md",
	} {
		content.WriteString(fmt.Sprintf("- `.universal-governance/SOPs/%s`\n", name))
	}

	path := filepath.Join(targetDir, ".agents", "skills", "ugc-governance", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content.String()), 0644)
}

func codexPrefixRules() []codexPrefixRule {
	return []codexPrefixRule{
		{Pattern: []string{"git", "push"}, Justification: "UGC approval packet required before git push."},
		{Pattern: []string{"git", "commit"}, Justification: "UGC approval packet required before git commit."},
		{Pattern: []string{"git", "reset"}, Justification: "UGC approval packet required before git reset."},
		{Pattern: []string{"rm", "-rf"}, Justification: "UGC approval packet required before destructive recursive delete."},
		{Pattern: []string{"npm", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"pnpm", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"yarn", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"gh", "release"}, Justification: "UGC approval packet required before release creation."},
		{Pattern: []string{"docker", "push"}, Justification: "UGC approval packet required before image publishing."},
		{Pattern: []string{"kubectl", "apply"}, Justification: "UGC approval packet required before cluster mutation."},
		{Pattern: []string{"terraform", "apply"}, Justification: "UGC approval packet required before infrastructure mutation."},
		{Pattern: []string{"vercel", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"netlify", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"firebase", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"gcloud", "run", "deploy"}, Justification: "UGC approval packet required before deploy."},
	}
}

func starlarkStringList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
