package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/universal-governance/ugc/engine/models"
)

type Emitter struct{}

func (e *Emitter) Emit(g *models.Governance, targetDir string) error {
	fmt.Println("Emitting Codex configuration...")

	var content strings.Builder
	content.WriteString(fmt.Sprintf("<!-- UGC-Source-Hash: %s -->\n\n", g.SourceHash))
	content.WriteString("# Universal Governance for OpenAI Codex\n\n")
	content.WriteString("This file is generated by UGC for OpenAI Codex. Codex reads repository `AGENTS.md` files as project guidance.\n\n")
	content.WriteString("## Canonical Governance Source\n\n")
	content.WriteString("- Source root: `.universal-governance/`\n")
	content.WriteString("- Mandatory entrypoint: `.universal-governance/AGENTS.md`\n")
	content.WriteString("- SOP index: `.universal-governance/SOPs/README.md`\n\n")
	content.WriteString("## Core Duties\n\n")
	content.WriteString("- Approval Gate: require explicit owner approval before gated, destructive, release, or architecture-changing work.\n")
	content.WriteString("- Stop Conditions: stop and report when source truth, approval, scope, or validation conflicts with the task.\n")
	content.WriteString("- Protected Surfaces: do not touch neighboring systems, secrets, cloud, billing, deploy, or git state unless approved.\n")
	content.WriteString("- Worklog: record material governance work in `Plans/worklog.md` when the active SOP requires it.\n")
	content.WriteString("- Destructive action warning: never overwrite, delete, reset, deploy, or publish without the applicable SOP approval.\n\n")
	content.WriteString("## Compiled Base Rules\n\n")
	content.WriteString(rewriteCodexSourcePaths(g.BaseRules))
	content.WriteString("\n\n## SOP Index\n\n")

	sops := append([]models.SOP(nil), g.SOPs...)
	sort.Slice(sops, func(i, j int) bool {
		return sops[i].Name < sops[j].Name
	})
	for _, sop := range sops {
		content.WriteString(fmt.Sprintf("- `%s`: `.universal-governance/SOPs/%s`\n", sop.Name, sop.Name))
	}

	if err := os.WriteFile(filepath.Join(targetDir, "AGENTS.md"), []byte(content.String()), 0644); err != nil {
		return err
	}
	if err := writeCodexConfig(g, targetDir); err != nil {
		return err
	}
	return writeCodexRules(g, targetDir)
}

func rewriteCodexSourcePaths(content string) string {
	content = strings.ReplaceAll(content, "`SOPs/", "`.universal-governance/SOPs/")
	content = strings.ReplaceAll(content, "(SOPs/", "(.universal-governance/SOPs/")
	return content
}

type codexPrefixRule struct {
	Pattern       []string
	Justification string
}

func writeCodexConfig(g *models.Governance, targetDir string) error {
	var content strings.Builder
	content.WriteString(fmt.Sprintf("# UGC-Source-Hash: %s\n", g.SourceHash))
	content.WriteString("# Project-local Codex config loads only after the project is trusted.\n")
	content.WriteString("approval_policy = \"on-request\"\n")
	content.WriteString("approvals_reviewer = \"user\"\n")
	content.WriteString("sandbox_mode = \"workspace-write\"\n")

	path := filepath.Join(targetDir, ".codex", "config.toml")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content.String()), 0644)
}

func writeCodexRules(g *models.Governance, targetDir string) error {
	var content strings.Builder
	content.WriteString(fmt.Sprintf("# UGC-Source-Hash: %s\n", g.SourceHash))
	content.WriteString("# Project-local Codex rules load only after the project is trusted.\n\n")

	for _, rule := range codexPrefixRules() {
		content.WriteString("prefix_rule(\n")
		content.WriteString(fmt.Sprintf("    pattern = %s,\n", starlarkStringList(rule.Pattern)))
		content.WriteString("    decision = \"forbidden\",\n")
		content.WriteString(fmt.Sprintf("    justification = %q,\n", rule.Justification))
		content.WriteString(")\n\n")
	}

	path := filepath.Join(targetDir, ".codex", "rules", "ugc.rules")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content.String()), 0644)
}

func codexPrefixRules() []codexPrefixRule {
	return []codexPrefixRule{
		{Pattern: []string{"git", "push"}, Justification: "UGC approval packet required before git push."},
		{Pattern: []string{"git", "commit"}, Justification: "UGC approval packet required before git commit."},
		{Pattern: []string{"git", "reset"}, Justification: "UGC approval packet required before git reset."},
		{Pattern: []string{"rm", "-rf"}, Justification: "UGC approval packet required before destructive recursive delete."},
		{Pattern: []string{"npm", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"pnpm", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"yarn", "publish"}, Justification: "UGC approval packet required before package publish."},
		{Pattern: []string{"gh", "release"}, Justification: "UGC approval packet required before release creation."},
		{Pattern: []string{"docker", "push"}, Justification: "UGC approval packet required before image publishing."},
		{Pattern: []string{"kubectl", "apply"}, Justification: "UGC approval packet required before cluster mutation."},
		{Pattern: []string{"terraform", "apply"}, Justification: "UGC approval packet required before infrastructure mutation."},
		{Pattern: []string{"vercel", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"netlify", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"firebase", "deploy"}, Justification: "UGC approval packet required before deploy."},
		{Pattern: []string{"gcloud", "run", "deploy"}, Justification: "UGC approval packet required before deploy."},
	}
}

func starlarkStringList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
